### ISSUE TITLE
Where is the version 4.0.0?

### ISSUE THREAD

**Issue by sd4324530** [ocpsoft/prettytime#101]
I can't find the 4.0.0 version at http://search.maven.org/, the newest version is 3.2.7.
Why?

**Comment by lincolnthree** [comment]
Strange. I think something happened to our release process. Let me verify this and make sure it gets out.

**Comment by lincolnthree** [comment]
Okay, it's released and should be sync'd to maven central repo within an hour or so. Sorry about that, looks like it got stuck in the release process the first time (a validation rule failed.)
