### ISSUE TITLE
How to translate prettytime-nlp recognition in other languages

### ISSUE THREAD

**Issue by LorenzoZanotto** [ocpsoft/prettytime#102]
How can I translate prettytime-nlp recognition in other languages?
Ex. if I put ("Ci vediamo domani") it will return tomorrow's date

**Comment by lincolnthree** [comment]
Unfortunately there is no way to translate this into another language without compiling the http://natty.joestelmach.com/ Natty date parser (what we use) with an ANTLR AST grammar from another language. I'd try getting in touch with those guys and see what they can do to accommodate.

**Comment by LorenzoZanotto** [comment]
Thank you @lincolnthree, please email me at hey@lorenzozanotto.com when you'll get news, I'll close the issue for now!
