### ISSUE TITLE
Supporting "TODAY" label when only date is available

### ISSUE THREAD

**Issue by rothschild86** [ocpsoft/prettytime#108]
I'm dealing with dates like this one: 06/23/2015 00:00:00 (time always at midnight).

So it made sense to comment out some units:

   private void initTimeUnits()
   {
      addUnit(new JustNow());
      //addUnit(new Millisecond());
      //addUnit(new Second());
      //addUnit(new Minute());
      //addUnit(new Hour());
      addUnit(new Day());
      addUnit(new Week());
      addUnit(new Month());
      addUnit(new Year());
      addUnit(new Decade());
      addUnit(new Century());
      addUnit(new Millennium());
   }

But this had a side effect of anything past "just now" showing as "1 day ago" instead of "today".

Anyone has an idea how to define this new rule for "today"? Thank you.

**Comment by lincolnthree** [comment]
My recommendation would be to replace the JustNow() unit with a Today() unit. Sorry for the SUPER late reply on this.

**Comment by rothschild86** [comment]
looking at all available units, i don't see a Today unit...

**Comment by sverrirs** [comment]
For posterity, here is how you can achieve this:

1. Create a new class Today
```
public class Today extends ResourcesTimeUnit implements TimeUnit {
    public Today() {
        this.setMaxQuantity(86400000L-1);
    }
    protected String getResourceKeyPrefix() {
        return "Today";
    }
    public boolean isPrecise() {
        return false;
    }
}
```

2. Create your own Resources file containing the new ResourceKey
```
// .. snip
{ "TodayPattern", "%u" },
{ "TodayFuturePrefix", "" },
{ "TodayFutureSuffix", "" },
{ "TodayPastPrefix", "" },
{ "TodayPastSuffix", "" },
{ "TodaySingularName", "today" },
{ "TodayPluralName", "today" },
{ "TodayFutureSingularName", "tomorrow" },
{ "TodayFuturePluralName", "tomorrow" },
{ "TodayPastSingularName", "yesterday" },
{ "TodayPastPluralName", "yesterday" },
// .. snip
```
3. Customize your PrettyTime instance to give your new `Today` class precedence
```
public class PrettyTimeUtils {
    private static PrettyTime mDayLimitedPrettyTime;

    public static PrettyTime GetDayLimited(){
        if( mDayLimitedPrettyTime == null){
            mDayLimitedPrettyTime = new PrettyTime(Locale.getDefault());
            mDayLimitedPrettyTime.clearUnits();

            Add(mDayLimitedPrettyTime, new Today());
            Add(mDayLimitedPrettyTime, new Day());
            Add(mDayLimitedPrettyTime, new Week());
            Add(mDayLimitedPrettyTime, new Month());
            Add(mDayLimitedPrettyTime, new Year());
            // Omitting Decade, Century and Millennium
        }
        return mDayLimitedPrettyTime;
    }

    private static void Add(PrettyTime p, ResourcesTimeUnit unit){
        p.registerUnit(unit, new ResourcesTimeFormat(unit));
    }
}
```

**Comment by rothschild86** [comment]
Perfect! 🙏
