### ISSUE TITLE
[FEATURE REQUEST] Java 8 support

### ISSUE THREAD

**Issue by sargue** [ocpsoft/prettytime#109]
Do you have any plans on forking a Java 8 (java.time) version?

**Comment by lincolnthree** [comment]
I think a Java 8 time update for the API would be a nice thing to do. What changes are required to support this? Sorry for the SUPER late reply.

**Comment by sargue** [comment]
Well, lots of changes I think. Not just supporting directly the new classes from java.time, you actually have functional overlapping of some classes like `TimeUnit` and `Duration`. And of course you can't have the same jar file supporting both Java 8 and pre-Java 8 so I think you would need a fork.

**Comment by EarthCitizen** [comment]
java.time.* support seems critical.

**Comment by TrentBrown** [comment]
I sure could use this, too.

**Comment by anhquande** [comment]
it would be great

**Comment by lincolnthree** [comment]
Hey all,

It's nice to see so much interest for this feature, but as of now we don't currently have any scheduled plans to do this development. I am, however, 100% willing to accept a pull request and release a new version that adds the feature if someone wants to do some development and unit testing for what is necessary. 

I'm happy to discuss how this new API would look if someone wants to get that conversation started and propose a design.

To start, I'm not sure a Fork is required. Why would this be necessary as opposed to creating adapters / facades for the duplicated modules?

Thanks!

**Comment by heruan** [comment]
For anyone that might be interested in Java 8 support, I'm working on a library to produce humanized strings for Java 8 `Temporal`s (such as `ZonedDateTime`). It does not have all the features of prettytime, but for the most simple use cases should be okay.

https://github.com/heruan/humanize

**Comment by MenoData** [comment]
@heruan Your project is not the first one. I myself have already started formatting of durations or relative times already in year 2012/3, see my lib [Time4J](https://github.com/MenoData/Time4J) which has a bridge to Java-8-types and actually supports 86 languages.

By the way, the problem with Java-8-interoperability is also that there is no duration type for mixed years, months, days, hours, minutes and seconds so I had to introduce a new duration type for enabling social media style formatting in Java-8, like this project ocpsoft/PrettyTime which is still focussed on old `java.util.Date`-API for historical reasons. That said, just supporting existing Java-8-types is not really enough.

**Comment by otaviocx** [comment]
> Hey all,
> 
> It's nice to see so much interest for this feature, but as of now we don't currently have any scheduled plans to do this development. I am, however, 100% willing to accept a pull request and release a new version that adds the feature if someone wants to do some development and unit testing for what is necessary.
> 
> I'm happy to discuss how this new API would look if someone wants to get that conversation started and propose a design.
> 
> To start, I'm not sure a Fork is required. Why would this be necessary as opposed to creating adapters / facades for the duplicated modules?
> 
> Thanks!

Hi @lincolnthree, I think I can help with this issue (Java 8 support). So, let's start the design? What do we need to do more than creating some format methods that receive the new classes? Thanks!

**Comment by joshfriend** [comment]
Android _finally_ has [desugaring for `java.time` APIs](https://developer.android.com/studio/write/java8-support) so that they can be used on older platforms.

The ThreeTenBP library used to have some helper methods for converting between `util.Date` and `java.time` stuff, but now that I no longer have that, it is exposing some spots in my app that lack `java.time` support, including PrettyTime.

**Comment by lincolnthree** [comment]
I'd still love to see a PR for this. Thanks for your interest in this library. Happy to help if anyone has questions / input.

**Comment by lincolnthree** [comment]
As far as I am concerned, creating methods to receive the new classes is all that is required (as a starting point.)

**Comment by joshfriend** [comment]
I tried to add `java.time` methods, but the project would not open properly in IntelliJ. There was no syntax highlighting or anything helpful so I gave up for now.

**Comment by gastaldi** [comment]
+1 to support for `java.time`. This is what I had to do to work with `java.time` classes: 

```java
        String formatDateTime(LocalDateTime dateTime) {
            PrettyTime p = new PrettyTime();
            return p.format(Date.from(dateTime.atZone(ZoneId.systemDefault()).toInstant()));
        }
```
