### ISSUE TITLE
Time Zone Issue.

### ISSUE THREAD

**Issue by shumin0809** [ocpsoft/prettytime#114]
Hi,

Is there a way I could setTimeZone for pretty time? Since I set UTC time zone for my time format, I would like to make time zone between pretty time and current time identical.

**Comment by mustafaberkaymutlu** [comment]
Take a look at this blog writing, if you use Joda-Time:
http://www.flowstopper.org/2012/11/prettytime-and-joda-playing-nice.html

**Comment by lincolnthree** [comment]
This is now possible in Version 5 of the API, which is about to be released.
