### ISSUE TITLE
Option to use a different default date/time?

### ISSUE THREAD

**Issue by wickedest** [ocpsoft/prettytime#115]
Thanks for the NLP date parser - I am looking at incorporating it into one of my projects, but I have a question.  If I have the code:

`final List<Date> dates = new PrettyTimeParser().parse("2015-09-16");`

Unfortunately, it returns a date with the current time:

`Tue Sep 16 23:54:29 IST 2015`

The original text does not have a time, but if the time was specified, the time would be important.  I would need to know time was not specified, or at least return 00:00:00.  It appears to be using the current time/date as a default.  Is there a way to specify the time/date to use when a date or time is not specified?  e.g. I may want "8pm" to evaluate to tomorrow, not today.  Or, I may want "2015-09-16" to evaluate to "Tue Sep 16 12:00:00 UTC 2015."

Any help is appreciated.

Kind Regards,
Jamie

**Comment by gmaijoe** [comment]
any updates?

**Comment by lincolnthree** [comment]
Hi folks,

Unfortunately we don't maintain the NLP module (It's actually a wrapper around Natty (natty.joestelmach.com).

I'd suggest looking into making fixes there. We're of course happy to accept pull requests.

Sorry we can't be of assistance here. Thanks for understanding!
