### ISSUE TITLE
Month format (Russian translation)

### ISSUE THREAD

**Issue by kevtom** [ocpsoft/prettytime#118]
Hi,

The Russian translation of the months gives us the following list:

января, февраля, марта, апреля, мая, июня, июля, августа, сентября, октября, ноября, декабря.

However, that way of spelling the months is only correct in Russian when you write the day before the month (e.g. 5 января 2016), and we need a format when the day is not written, i.e. just month + year (not day + month + year). Each spelling is different and we need to use the following list:

январь, февраль, март, апрель, май, июнь, июль, август, сентябрь, октябрь, ноябрь, декабрь.

How can I use the above spelling of the months (январь 2016)? 

Thanks.

**Comment by lincolnthree** [comment]
The easiest way is probably to implement your own resource bundle and set your own Locale code to load it (see translation guide: http://www.ocpsoft.org/prettytime/#section-14 )

Name it something like Resources_RU_custom.java, then just set the locale when creating your PrettyTime instance. It will load your bundle:

PrettyTime p = new PrettyTime(new Locale("RU_custom");

You can probably base your bundle on the existing Russian bundle for convenience:

https://github.com/ocpsoft/prettytime/blob/master/core/src/main/java/org/ocpsoft/prettytime/i18n/Resources_ru.java

I hope this helps.

**Comment by lincolnthree** [comment]
To answer your second question and remove days. You should remove the units you are not interested in seeing from the PrettyTime units configuration:

https://github.com/ocpsoft/prettytime/blob/master/core/src/main/java/org/ocpsoft/prettytime/PrettyTime.java#L611

`p.removeUnit(Minutes.class)`

~Lincoln

**Comment by lincolnthree** [comment]
Closing this. Please reopen if I did not answer your questions! Thanks :)
