### ISSUE TITLE
Add possibility to provide diffrent values for past and future name and pluralName

### ISSUE THREAD

**Issue by ssaarinen** [ocpsoft/prettytime#12]
Hi,

I started making Finnish translation for pretty time but realized that Finnish being awkward language needs different values for name/pluralName depending whether the duration is in the past or future.
eg.
1 minute ago = 1 minuutti sitten
1 minute from now = 1 minuutin päästä
3 minutes ago = 3 minuuttia sitten
3 minutes from now  = 3 minuutin päästä

As you can (probably ;) see Finnish word minuutti (= minute) conjugation is different for past and future and it also depends if the duration is singular or not. So using just the past and future suffix leads to grammatically incorrect durations.

I could give this a stab my self but was just wondering what would be the best way to tackle this.

**Comment by ntobekoMkhize** [comment]
Is there a way to return 1 day ago as yesterday from the standard resource bundle? I see this considered in this thread
