### ISSUE TITLE
call to calculatePreciseDuration should not mutate

### ISSUE THREAD

**Issue by kosii** [ocpsoft/prettytime#122]
The current implementation of `calculatePreciseDuration` mutates the `PrettyTime` instance by assigning the current time to `this.reference` if it was `null`, which is pretty unexpected (and undocumented). 

Is this something to fix? If yes, which way to proceed? Documenting the current behavior or declaring a local variable like this: 

      Date reference = this.reference;

**Comment by lincolnthree** [comment]
Yeah, this definitely seems like a bug. Care to send in a PR? Sorry for the late reply. Just getting caught up on issues now.

**Comment by kosii** [comment]
it's done, does it look ok to you?

**Comment by lincolnthree** [comment]
Looks great, thank you! I'll work on getting a new release out in the next few days/week.
