### ISSUE TITLE
Duration amount is not being localized

### ISSUE THREAD

**Issue by faifai21** [ocpsoft/prettytime#123]
Hi there,

I'm using PrettyTime on Android, and I'm not sure what the extent of the issue of is. I know that for Arabic locales, the duration amount is being displayed using roman numerals, as opposed to being localized:

![untitled](https://cloud.githubusercontent.com/assets/4616968/13504880/552f90ec-e12b-11e5-9a90-12c0092be9dd.png)

![untitled 2](https://cloud.githubusercontent.com/assets/4616968/13504886/5b2155ee-e12b-11e5-85a7-bf49325d593c.png)

Is there a setting I'm missing?

**Comment by lincolnthree** [comment]
Uh oh. this looks like a feature I'm not sure we support yet. I'd be happy to accept a PR that made this work! 

I wonder how much work it would take to implement this, or if there is some native localization feature for numerics? Do you know?

**Comment by lincolnthree** [comment]
This should now be working as of Version 5 of the API, soon to be released.
