### ISSUE TITLE
4.0.1.Final may not be updated in Maven

### ISSUE THREAD

**Issue by rogerhu** [ocpsoft/prettytime#128]
The maven-metadata.xml only contains 4.0.0.Final:

http://jcenter.bintray.com/org/ocpsoft/prettytime/prettytime-nlp/

See the contets:
http://jcenter.bintray.com/org/ocpsoft/prettytime/prettytime-nlp/maven-metadata.xml

**Comment by lincolnthree** [comment]
Thanks for pointing this out. I'll be releasing a new version shortly that should hopefully correct this.

**Comment by curiousily** [comment]
Hi, 

I am experiencing the same issue. Would be great to release new version.

Thanks for the great lib!

**Comment by lincolnthree** [comment]
***Issue cleanup*** Thanks for filing this issue. We are cleaning old issues from the repository. If the issue is still reproducible, please re-open with a test case to reproduce the behavior.
