### ISSUE TITLE
issue with punctuation marks, "!"

### ISSUE THREAD

**Issue by axos88** [ocpsoft/prettytime#132]
Sometimes ago is not interpreted correctly, and the date is calculated into the future instead of the past.

```
scala> new PrettyTimeParser().parse("4 hours ago!");
res2: java.util.List[java.util.Date] = [Mon Apr 25 17:44:29 CEST 2016]

scala> new PrettyTimeParser().parse("4 hours ago");
res3: java.util.List[java.util.Date] = [Mon Apr 25 09:44:31 CEST 2016]

scala> new PrettyTimeParser().parse("4 hours ago !");
res4: java.util.List[java.util.Date] = [Mon Apr 25 09:44:34 CEST 2016]

scala> new PrettyTimeParser().parse("4 hours ago.");
res5: java.util.List[java.util.Date] = [Mon Apr 25 09:44:37 CEST 2016]

scala> new PrettyTimeParser().parse("4 hours ago!");
res6: java.util.List[java.util.Date] = [Mon Apr 25 17:44:40 CEST 2016]
```

**Comment by ginccc** [comment]
i encountered the same problem when trying the example from the website:

```
List<Date> dates = new PrettyTimeParser().parse("I'm going to the beach in three days!");
```
it actually parses the date wrong (giving me current day at 3 o'clock instead) when there is another symbol attached to the "days". Without any punctuation it works fine.

**Comment by ginccc** [comment]
The underlying parser library com.joestelmach/natty seems to be outdated since the latest version of natty can parse words connected to punctuation whereas the natty code that comes with prettytime-nlp:4.1.0 doesn't parse this correctly.

**Comment by lincolnthree** [comment]
Natty has been updated in Version 5.

***Issue cleanup*** Thanks for filing this issue. We are cleaning old issues from the repository. If the issue is still reproducible, please re-open with a test case to reproduce the behavior.
