### ISSUE TITLE
POM references snapshot

### ISSUE THREAD

**Issue by zacharywhitley** [ocpsoft/prettytime#133]
the pom file at

https://repo1.maven.org/maven2/org/ocpsoft/prettytime/prettytime-nlp/4.0.1.Final/prettytime-nlp-4.0.1.Final.pom

references prettytime 4.0.1-SNAPSHOT as its parent.

**Comment by lincolnthree** [comment]
***Issue cleanup*** Thanks for filing this issue. We are cleaning old issues from the repository. If the issue is still reproducible, please re-open with a test case to reproduce the behavior.
