### ISSUE TITLE
Wrong "minute" abreviation for Polish

### ISSUE THREAD

**Issue by JMSuarez88** [ocpsoft/prettytime#135]
Hi there, I have a report from Polish translator suggesting to change the current abbreviation for minute due to they don't use a full stop after it.
I don't know if you should change it or if I could do it via pull request.

**Current**

> min.

**New**

> min

**Path to file**

> https://github.com/ocpsoft/prettytime/blob/master/core/src/main/java/org/ocpsoft/prettytime/i18n/Resources_pl.java (line 77 and 78)

**Comment by lincolnthree** [comment]
Thanks again for this issue and PR!

***Issue cleanup*** Thanks for filing this issue. We are cleaning old issues from the repository. If the issue is still reproducible, please re-open with a test case to reproduce the behavior.
