### ISSUE TITLE
format returns "1 day ago" instead of "today"

### ISSUE THREAD

**Issue by MilkBiscuit** [ocpsoft/prettytime#137]
```
import org.ocpsoft.prettytime.PrettyTime;
......
    private static PrettyTime daysLapsed = new PrettyTime();
    static {
        daysLapsed.clearUnits();
        addUnit(daysLapsed, new Day());
        addUnit(daysLapsed, new Week());
        addUnit(daysLapsed, new Month());
        addUnit(daysLapsed, new Year());
    }
......


    public static String formatDaysLapsed(Context context, Date date) {
        return daysLapsed.format(date);
    }

```

If we pass a date with value of today, daysLapsed.format(date) will return "1 day ago" instead of "today".

**Comment by sverrirs** [comment]
See https://github.com/ocpsoft/prettytime/issues/108#issuecomment-587193166

**Comment by lincolnthree** [comment]
***Issue cleanup*** Thanks for filing this issue. We are cleaning old issues from the repository. If the issue is still reproducible, please re-open with a test case to reproduce the behavior.
