### ISSUE TITLE
I18N

### ISSUE THREAD

**Issue by ghaseminya** [ocpsoft/prettytime#141]
Hi
How to add new language to i18n list ?(http://www.ocpsoft.org/prettytime/#section-13)
I want to add Persian translation to main project.
Thanks.

**Comment by ghaseminya** [comment]
https://github.com/ghaseminya/prettytime/blob/master/core/src/main/java/org/ocpsoft/prettytime/i18n/Resources_fa

**Comment by lincolnthree** [comment]
Hi there!

Thanks for wanting to contribute! The easiest way is to open a pull request with your resources file located here:

https://github.com/ocpsoft/prettytime/tree/master/core/src/main/java/org/ocpsoft/prettytime/i18n

It would be extra helpful if you could also include a test, here: 

https://github.com/ocpsoft/prettytime/tree/master/core/src/test/java/org/ocpsoft/prettytime

Does that answer your question? 

Thanks again!

**Comment by ghaseminya** [comment]
Thanks @lincolnthree 
Create a new pull request

**Comment by lincolnthree** [comment]
This PR has been merged. ***Issue cleanup*** Thanks for filing this issue. We are cleaning old issues from the repository. If the issue is still reproducible, please re-open with a test case to reproduce the behavior.
