### ISSUE TITLE
ResourcesTimeUnit should be either immutable or not use maxQuantity and millisPerUnit in hashCode()

### ISSUE THREAD

**Issue by mkouba** [ocpsoft/prettytime#152]
Time units are used as keys in a `LinkedHashMap`!
https://github.com/ocpsoft/prettytime/blob/master/core/src/main/java/org/ocpsoft/prettytime/PrettyTime.java#L68

As a result, if you do:
```java
PrettyTime prettyTime = new PrettyTime();
prettyTime.getUnit(JustNow.class).setMaxQuantity(1000L * 2L);
prettyTime.format(new Date());
```
you will most probably get NPE because the `TimeFormat` for `JustNow` will not be found.

A workaround is to replace the unit:
```java
PrettyTime prettyTime = new PrettyTime();
TimeFormat timeFormat = prettyTime.removeUnit(JustNow.class);
JustNow justNow = new JustNow();
justNow.setMaxQuantity(1000L * 2L);
prettyTime.registerUnit(justNow, timeFormat);
prettyTime.format(new Date());
```

**Comment by mkouba** [comment]
Also note that it's a regression in 4.0.0.Final.

**Comment by ZumiKua** [comment]
Is there any plan to fix this issue?

**Comment by JayDi85** [comment]
Still actual for 4+ versions.. 3+ works fine.

You can't change just now interval -- it's broke the code.
Change interval:
```
timeFormater.setLocale(Locale.ENGLISH);
JustNow jn = timeFormater.getUnit(JustNow.class);
jn.setMaxQuantity(1000L * 30L); // 30 seconds gap (show "just now" from 0 to 30 secs)
```
Broken by NPE error:
```
Date d = ...;
timeFormater.format(d) // return NPE, can't find just now (it's 60 seconds gap by default, but we changed to 30 secs)
```
You must add special method in PrettyTime to change default TimeUnit settings like:
`PrettyTime.updateTimeUnit(oldTimeUnit, newTimeUnit);`

**Comment by lincolnthree** [comment]
This has been fixed in Version 5. TimeUnits now use a uniquely generated ID to identify themselves in the map. Thanks for the issue!
