### ISSUE TITLE
What's the difference between PrettyTime NLP and Natty?

### ISSUE THREAD

**Issue by jdorleans** [ocpsoft/prettytime#153]
I'm considering using Natty to parse date/time and I found PrettyTime wrapping it in one file implementation. After reading the code it isn't very clear what it's trying to achieve. I'd appreciate if someone could explain what's the main difference of using prettytime nlp instead of natty for that particular purpose.

**Comment by lincolnthree** [comment]
It's just a thin wrapper to try to consolidate the API. You can use either. I'd suggest using Natty if you're going to be tweaking or pushing back contributions.

**Comment by lincolnthree** [comment]
The PrettyTime NLP project probably needs to be officially retired. It was set up in hopes of promoting Natty and bringing more contributors in, but that didn't happen.

**Comment by lincolnthree** [comment]
Thanks for asking!
