### ISSUE TITLE
Parsing 3 digit long numbers not working

### ISSUE THREAD

**Issue by recon88** [ocpsoft/prettytime#166]
Using parseSyntax() fails when giving it 3 digit long numbers.
Examples with the current time around 20:12:

```
Working:
parseSyntax("25 hours")
08.07.2018 21:11:40

Not Working:
parseSyntax("120 hours")
07.07.2018 12:00:00

Working:
parseSyntax("99 days")
14.10.2018 20:12:21

Not Working:
parseSyntax("400 days")
07.07.2018 00:00:00
```

Edit:
Using plain Natty works fine.

**Comment by lincolnthree** [comment]
Version 5 of PrettyTime includes Natty 0.13.0, which may fix this issue.

***Issue cleanup*** Thanks for filing this issue. We are cleaning old issues from the repository. If the issue is still reproducible, please re-open with a test case to reproduce the behavior.
