### ISSUE TITLE
4.0.2 appears in maven central, no git commits/release code?

### ISSUE THREAD

**Issue by talios** [ocpsoft/prettytime#167]
I notice that 4.0.2 is appearing in Maven Central since May 22nd, but there's no evidence of the release/commits in the git repo here, or the website:

  https://search.maven.org/#search%7Cga%7C1%7Cprettytime

Is this a legitimate release, and if so -  can the commits/release notes/tags be pushed to github?

**Comment by talios** [comment]
Are the missing commits/PR merges going to fixed so that the repo shows some form of 4.0.2 releasing existing - maybe re-merge the PRs and release 4.0.3 to get things back in sync?

**Comment by talios** [comment]
No movement to resolve this? I under the various PR's that went into the 4.0.2 release are actually still merged, so we just need to re-release ( probably best as 4.0.3 )?

**Comment by talios** [comment]
I see there's now a 4.0.4 release in Maven central, yet no release here on github, no mention of it in the README ( which still mentions 4.0.1! ), and the CHANGELOG only mentions version 1.x.

Can we get some of this information updated? What's changed in 4.0.4?

**Comment by lincolnthree** [comment]
Yes, these are legitimate patch releases, and the missing commits for 4.0.4 have been pushed. Though I see some irony in them going missing. 

Note, the commit history on GitHub shows all changes that have been made to the code to date. No commits are missing between what's in GitHub and what's published in maven.
