### ISSUE TITLE
Unable to get the latest release

### ISSUE THREAD

**Issue by panos-stavrianos** [ocpsoft/prettytime#169]
Hello, i am trying to get the latest release "4.0.1.Final" but i am getting some older version. I look at the jar and all files are modified at 2015. 
Actually i want to use Greek locale and the Resources_el file it's missing (as added about 9 months ago)
At my dependencies i have
`implementation 'org.ocpsoft.prettytime:prettytime:4.0.1.Final'`
What i am doing wrong?

**Comment by lincolnthree** [comment]
***Issue cleanup*** Thanks for filing this issue. We are cleaning old issues from the repository. If the issue is still reproducible, please re-open with a test case to reproduce the behavior.
