### ISSUE TITLE
getRecurInterval returns only the first (wrong) interval 

### ISSUE THREAD

**Issue by recon88** [ocpsoft/prettytime#171]
Let's say I want to parse "every Sunday at 9PM" and Today is Saturday.
getRecurInterval() then returns the time between Today (Saturday) and Sunday 9PM.
But what  it should return is the interval between the first "Sunday 9PM" and the second "Sunday 9PM".

**Comment by lincolnthree** [comment]
Issues with NLP should be submitted to: https://github.com/joestelmach/natty

***Issue cleanup*** Thanks for filing this issue. We are cleaning old issues from the repository. If the issue is still reproducible, please re-open with a test case to reproduce the behavior.
