### ISSUE TITLE
Cannot find most of the API in the released JAR

### ISSUE THREAD

**Issue by andreaferretti** [ocpsoft/prettytime#172]
Hi, I am trying to figure out how to use PrettyTime to parse dates in italian.

I have a dependency on "prettytime-nlp", version "4.0.2.Final" from Sonatype. I am trying to do

```java
import org.ocpsoft.prettytime.PrettyTime;
PrettyTime p = new PrettyTime(new Locale("it"));
```

but it seems that `org.ocpsoft.prettytime.PrettyTime` is just not in the JAR. I can instantiate a `org.ocpsoft.prettytime.nlp.PrettyTimeParser`, but I do not see a way to set the language to italian for that constructor

**Comment by lincolnthree** [comment]
Apologies for the delay. PrettyTime NLP is a wrapper around a third party extension. You need to include org.ocpsoft.prettytime:prettytime as well, to get the org.ocpsoft.prettytime.PrettyTime class definition. However, NLP only functions for English at this time. Please see link to the source project for additional resources. No translation efforts for NLP have been contributed by the community.
