### ISSUE TITLE
SimpleTimeFormat.applyPattern localization bug with quantity parameter

### ISSUE THREAD

**Issue by rasoulMrz** [ocpsoft/prettytime#174]
Hi.
I'm using prettytime version 4.0.2.Final.
I found a localization bug with this part of code from SimpleTimeFormat.java at line 91:

```
  private String applyPattern(final String sign, final String unit, final long quantity)
   {
      String result = getPattern(quantity).replaceAll(SIGN, sign);
      result = result.replaceAll(QUANTITY, String.valueOf(quantity));
      result = result.replaceAll(UNIT, unit);
      return result;
   }
```

As you see the method String.valueOf() is used to convert the quantity parameter to string value. However, this method does not take care of localization.
I suggest using String.format(locale, "%d", quantity) instead.

This fix, if applied, will change "5" in the string "5 روز پیش" to "۵ روز ‍‍ پیش".
(The text means "5 days ago" in Persian)

**Comment by lincolnthree** [comment]
Implemented in version 5. Thanks for the great idea!
