### ISSUE TITLE
Just get "Days Ago"

### ISSUE THREAD

**Issue by HermanKayy** [ocpsoft/prettytime#178]
Is there a way to just get back "Days Ago"? For example if it's 7 days instead of it giving me back "1 week" ago it'll give me back 7 days ago. Instead of 1 month ago it'll give me back 30 days ago, etc.

**Comment by lincolnthree** [comment]
@HermanKayy Yes, you need to manually pass only the `Day` time unit to the `PrettyTime` configuration, after removing all others:

```
PrettyTime p = new PrettyTime();
p.clearUnits();
p.addUnit(new Day());
p.format(new Date());
```

**Comment by lincolnthree** [comment]
Working on an easier API for this in Version 5.

**Comment by lincolnthree** [comment]
New API here: https://github.com/ocpsoft/prettytime/commit/08894358b6b5ee1b587a0527fc42e05b60d1c57b
