### ISSUE TITLE
Arabic numbers should use Eastern Arabic numerals instead of Western ones

### ISSUE THREAD

**Issue by mhmdanas** [ocpsoft/prettytime#195]
For example, `١` should be used instead of `1`. I'd like to open a PR for this myself, but I'm unfamiliar with the structure of the code, so it'd be a bit difficult for me to do so.

**Comment by lincolnthree** [comment]
This is resolved in version 5 of the PrettyTime API. Thanks for filing this issue!


***Issue cleanup*** Thanks for filing this issue. We are cleaning old issues from the repository. If the issue is still reproducible, please re-open with a test case to reproduce the behavior.
