### ISSUE TITLE
NoClassDefFoundError on android API level < 26

### ISSUE THREAD

**Issue by albertobasso** [ocpsoft/prettytime#204]
Dear developers, 
using the latest version of the library (5.0.0.Final) I'm unable to resolve the crash: **java.lang.NoClassDefFoundError: Failed resolution of: Ljava/time/Instant;**
On Android sdk documentation https://developer.android.com/reference/java/time/Instant.html I see in the upper right corner "added in API level 26" which means the class is not available on older android devices.
So... do you'll fix this issue adding a backward compatible method for android < 8.0? Otherwise is maybe necessary report that this release works only with API level >= 26 of android.
Thanks for your job!
Alb.

**Comment by lincolnthree** [comment]
Hello!

Have you tried following the instructions linked in the README in this repo that describe how to use in API levels <26?

https://github.com/ocpsoft/prettytime#android
https://developer.android.com/studio/write/java8-support#library-desugaring

If that is what you're looking for, we could certainly make this notice more visible.

Thanks!

**Comment by lincolnthree** [comment]
Closing, as this is already documented. If something is wrong with what's we've documented, please feel free to comment or open a new issue. Thanks.
