### ISSUE TITLE
Tags for releases?

### ISSUE THREAD

**Issue by nedtwigg** [ocpsoft/prettytime#208]
Thanks very much for publishing this great opensource library. Beggars can't be choosers, but I meekly ask for tagged releases. My security hackles raise when mavencentral has a release which I can't audit against the source repo.

**Comment by lincolnthree** [comment]
But they *are* tagged ;)

JK. They are /now/. Seems they haven't been getting pushed by the CI release process. Fixed. 

Thanks for pointing this out. Much appreciated.
