### ISSUE TITLE
One minute is wrongly translated in Romanian

### ISSUE THREAD

**Issue by iamthesenate1** [ocpsoft/prettytime#210]
As the title says, one minute is translated as "o minuta" when it should be "un minut"

**Comment by gastaldi** [comment]
@iamthesenate1 mind sending a PR fixing that? You should change https://github.com/ocpsoft/prettytime/blob/master/core/src/main/java/org/ocpsoft/prettytime/i18n/Resources_ro.java AFAIK

**Comment by iamthesenate1** [comment]
> @iamthesenate1 mind sending a PR fixing that? You should change https://github.com/ocpsoft/prettytime/blob/master/core/src/main/java/org/ocpsoft/prettytime/i18n/Resources_ro.java AFAIK

Thanks

**Comment by lincolnthree** [comment]
Merged. Will be in next release.
