### ISSUE TITLE
36-48 hours resolved as `2 days ago` instead of `1 day ago`

### ISSUE THREAD

**Issue by linama** [ocpsoft/prettytime#219]
Hey so during our testing we noticed that the time that's 36 - 48 hours before the current time, the time string will return '2 days ago' instead of '1 day ago'. We are wondering if it's supposed to be '1 day ago' for this case?? Since 2 days ago should be anything that's earlier than 48hours to 72hours. please let me know. thanks!

**Comment by lincolnthree** [comment]
You can change the tolerance by overriding / providing your own TimeFormat and configuring the PrettyTime instance to use it.
