### ISSUE TITLE
[LOW] Typo regarding "months"

### ISSUE THREAD

**Issue by 0x5ECF4ULT** [ocpsoft/prettytime#220]
When setting the locale to `de` there is a typo when handling months. 1 month becomes "1 Monatn" (comparable to "monhs") instead of "1 Monat" (month). Please see the attached issue for a detailed explaination:

https://github.com/TeamNewPipe/NewPipe/issues/6508

**Comment by lincolnthree** [comment]
@0x5ECF4ULT Hey there. Thanks for the issue report. Mind sending a PR to fix this? It would be super awesome!

**Comment by obecker** [comment]
Apparently something's wrong with the `isPlural()` method used in the `decorate`/`decorateUnrounded` implementations in `Resources_de.DeTimeFormat`. So it might help to know how the prettytime API is used in your case.

**Comment by lincolnthree** [comment]
Closed via https://github.com/ocpsoft/prettytime/pull/229
