### ISSUE TITLE
Crashes on Android after 4.0.5.FINAL => 5.0.3.FINAL

### ISSUE THREAD

**Issue by Zhuinden** [ocpsoft/prettytime#231]
After updating from 4.0.5-FINAL to 5.0.3-FINAL, Resources_DE.java is missing in release variant.

Works in English, crashes in Deutsch (German).

**Comment by Zhuinden** [comment]
https://github.com/ocpsoft/prettytime/commit/602b3a9bb6efbc9f7032fb7307f4866227aa4135#diff-890e315590328edb1e4b44fe79ca21829fa19524a8f900da5cb8d3874f575286R1

Solution is to add Proguard rule

`-keep class org.ocpsoft.prettytime.i18n.**`

Because whatever is in the repo is not working

**Comment by lincolnthree** [comment]
Ah, actually I do see we are missing a '.' in the path. That could be the issue.

**Comment by lincolnthree** [comment]
Closing as out of date. Please reopen if this is still an issue.
