### ISSUE TITLE
Add reference date to NLP PrettyTimeParser

### ISSUE THREAD

**Issue by sp4ce** [ocpsoft/prettytime#235]
The parser already supports it, so it's only about being able to send a reference date into it via the class `PrettyTimeParser` and the associated `parse` method.

**Comment by lincolnthree** [comment]
Hey @sp4ce - Thanks so much for sending this PR! Sorry again for the delay in responding. As I mentioned it's been a tough summer but I'm getting back into things now :) Cutting a new release with this today.
