### ISSUE TITLE
Weird class

### ISSUE THREAD

**Issue by gastaldi** [ocpsoft/prettytime#245]
It seems that this class is in the wrong place? 
https://github.com/ocpsoft/prettytime/blob/master/%C9%99sas/src/%C9%99sas/java/org/ocpsoft/g%C3%B6z%C9%99l%20vaxt/i18n/Resources_az.java   

/cc @lincolnthree

**Comment by Nizami20052022** [comment]
Why?

**Comment by Nizami20052022** [comment]
This is my mistake

**Comment by lincolnthree** [comment]
No worries. It should be fixed now thanks to @gastaldi !
