### ISSUE TITLE
Japanese and Finnish locales and proguard

### ISSUE THREAD

**Issue by Rexee** [ocpsoft/prettytime#265]
These 2 locales "org.ocpsoft.prettytime.i18n.Resources_fi" and "org.ocpsoft.prettytime.i18n.Resources_ja" use reflection to get unit names:
```
 private String getUnitName(TimeUnit unit)
      {
         return unit.getClass().getSimpleName();
      }
```
As result, if we use Proguard, then there will be crashes because Proguard will obfuscate names of these classes.
There is 2 possible solutions:
- Solution 1: rewrite these 2 locales to works like other locales
- Solution 2: add in proguard rules following line:
`-keep public class * implements org.ocpsoft.prettytime.TimeUnit`

I think Solution 1 is more correct, but Solution 2 is more easy

**Comment by lincolnthree** [comment]
I agree. These should be re-written. Feel like sending a PR? Thanks for the issue and sorry for the delay!

**Comment by matteinn** [comment]
I confirm solution 2 works fine as a workaround

**Comment by lincolnthree** [comment]
Hey @matteinn Thanks for your solution! I will add this to the ProGuard file: https://github.com/ocpsoft/prettytime/blob/master/core/src/main/resources/META-INF/proguard/prettytime.pro
