### ISSUE TITLE
Misleading JavaDoc for PrettyTime#format(Date) and PrettyTime#formatUnrounded(Date)

### ISSUE THREAD

**Issue by mwanji** [ocpsoft/prettytime#39]
The JavaDoc for these methods states:

> If {code then} is null, it will default to {code new Date()}

But the code throws an exception:

``` java
if (then == null)
         throw new IllegalArgumentException("Date to format must not be null.");
```

The [test](https://github.com/mwanji/prettytime/blob/master/core/src/test/java/org/ocpsoft/prettytime/PrettyTimeTest.java#L59) expects the exception.

**Comment by lincolnthree** [comment]
Sorry for that. I've actually just release version 4.0 that fixes not only
the documentation, but also actually allows nulls again :)

On Mon, Dec 22, 2014 at 4:40 AM, Moandji Ezana <notifications@github.com>
wrote:

> Thanks! However, I think the javadoc for PrettyTime#formatUnrounded(Date)
> still has the same problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ocpsoft/prettytime/issues/39#issuecomment-67818288>.
>



-- 
Lincoln Baxter, III
http://ocpsoft.org
"Simpler is better."
