### ISSUE TITLE
Time unit added twice with PrettyTime.calculatePreciseDuration(Date)

### ISSUE THREAD

**Issue by romming** [ocpsoft/prettytime#84]
Getting the output "40 minutes 1 minute ago", when I really should get "40 minutes ago" or "41 minutes ago". Using the latest version (3.2.5.Final).

Here's my code (Scala):
<pre><code>
val prettyTime = new PrettyTime();
prettyTime.clearUnits();
val minutes = new Minute();
prettyTime.registerUnit(minutes, new ResourcesTimeFormat(minutes));
System.out.println(prettyTime.format(prettyTime.calculatePreciseDuration(DateUtils.addSeconds(DateUtils.addMinutes(new Date(), -40), -10))));
</code></pre>

I think the problem could be avoided by modifying the loop condition on line 225 from just checking for 0 equality to also checking whether the latest duration has the smallest unit - would that make sense? In other words, execute if duration.getDelta() != 0 or duration.getUnit().getClass() != units.keySet().iterator().next().getClass().

Thanks!

**Comment by lincolnthree** [comment]
This is resolved in 4.0.0.Final - releasing soon.
