### ISSUE TITLE
Add manifest entries in jar to make it a valid OSGi bundle

### ISSUE THREAD

**Issue by kitschen** [ocpsoft/prettytime#87]
To make the normal prettytime jar a valid OSGi bundle, only a few headers must be added in the MANIFEST.MF file. 
This is typically done automatically on build by using for example the maven-bundle-plugin (if you use maven for build). It can also be done post-build.

This would allow to use prettytime in an OSGi environment!

**Comment by amergey** [comment]
I would also be interested to use prettytime in osgi environment. 
I have created a pull request (#100) adding configuration to the POM in order to build prettytime with OSGI manifest

**Comment by lincolnthree** [comment]
(Merged PR)
