### ISSUE TITLE
Creation of PrettyTime Objects very slow

### ISSUE THREAD

**Issue by damn** [ocpsoft/prettytime#89]
Creating 1000 PrettyTime objects takes 250 ms on my machine. It showed up as a bottleneck for our page. 

Re-using the same Object and formatting 1000 dates takes only 12 ms, so a workaround would be to re-use the same PrettyTime object on each request or cache it for a short period.

**Comment by lincolnthree** [comment]
I don't think we will fix this issue. Supporting i18n is at odds with object creation performance. Recommendation is as workaround suggests, don't create too many objects if possible :)
