### ISSUE TITLE
Should I be able to parse "04 Dec 2014 pm 1:58" ?

### ISSUE THREAD

**Issue by amitMist** [ocpsoft/prettytime#91]
I am in need to parse & get proper date format from some ill formatted date-time string. e.g. "04 Dec 2014 pm 1:58".  When I do parse this example string, I get : "Thu Dec 04 02:59:33 ALMT 2014"  which is I believe my current time stamp.
Can any of you kindly tell me, whether should I expect PrettyTime to parse for this type of ill-formatted string? 

Btw, its a great library. Thanks so far. :)

**Comment by nickgrealy** [comment]
Not far off... if you put the `pm` in the right place -> http://natty.joestelmach.com/try.jsp => `04 Dec 2014 1:58pm`
