### ISSUE TITLE
About ISO-639-1 code of Ukrainian language

### ISSUE THREAD

**Issue by MenoData** [ocpsoft/prettytime#94]
Your resources for Indonesian and Ukrainian refer to the language codes "in" and "ua". I am wondering if this really works in nowadays usage because the websites

http://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

or

http://www.mathguide.de/info/tools/languagecode.html

list the codes "id" and "uk". Is this a problem for users of PrettyTime-library? Well, "in" seems to be an outdated variant, but "ua"???

**Comment by MenoData** [comment]
About Indonesian: Although "id" is definitely more correct than "in" (latter form is just an outdated identifier), current behaviour is okay because Java automatically changes any input "id" to "in" in the constructors of `java.util.Locale` (I assume that was for preserving backwards compatibility).

But the case of Ukrainian is definitely a bug. Right is "uk".

**Comment by lincolnthree** [comment]
Fixed Ukraine. Thanks!
