### ISSUE TITLE
Thymeleaf Integration

### ISSUE THREAD

**Issue by dtrunk90** [ocpsoft/prettytime#95]
Please make PrettyTime available for Thymeleaf:
`<p th:text="${#prettytime.format(date)}">1 year ago</p>`

**Comment by bphilipnyc** [comment]
For anyone looking, you can alternatively do something like

`<span th:text="${T(com.domain.util.SomeUtil).getPrettyDate(bean.theDate)}">(time ago)</span>`

and

```
public static String getPrettyDate(Date date) {
    PrettyTime pretty = new PrettyTime();
    return date != null ? pretty.format(date) : "";
}
```

with the caveat about unit testing static methods blah blah blah

**Comment by IBN224** [comment]
Thanks it perfectly work for me
