### ISSUE TITLE
Representing time ago similar to instagram.

### ISSUE THREAD

**Issue by krngrvr09** [ocpsoft/prettytime#96]
![rsz_screenshot_2014-12-21-01-33-57](https://cloud.githubusercontent.com/assets/5905966/5523275/42ba88aa-89ec-11e4-87ef-d7c740630a98.png)

I want to write time ago, like instagram does (the image above).
I have figured out how to shorten "2 weeks ago" into "2w". For that I have created a new class extending ListResourceBundle ( ``Resources_en_short``), and replaced "weeks", by "w". 

I now have the following questions:

1. Since there is an image resource involved - look at the clock above - I wanted to create a CustomView, that will put that clock by default. Is this diverting too much from the structure and goal of the library?

2. If I remove the 'space' between "2" and "w", then how do I remove that just for ``Resource_en_short`` and not for other classes?

I hope I am clear enough.
Thanks.

**Comment by lincolnthree** [comment]
Hi There,

First, I'm very sorry that I missed this question for so long! It looks like you are doing everything correctly. As long as you are only using the en_short locale, your dates and times should use the resource bundle you've provided.

To remove the space, I think you need to use a different. I think you can remove the space in your ResourceBundle, but I need to see your code. You need to remove the spaces in the format patterns:

http://www.ocpsoft.org/prettytime/translate-for-your-language/#section-14

~Lincoln
