### ISSUE TITLE
Represent time / clock as text

### ISSUE THREAD

**Issue by frmz** [ocpsoft/prettytime#97]
It would be really great to be able to convert a date into text, especially time, so something like "ten past eleven" or "three o'clock". I could fork and implement this for english.

**Comment by lincolnthree** [comment]
Yeah, this would be an interesting feature. Sorry for the late reply. I think this might need to be done as a separate module at first, then we can try to bring it into the primary PrettyTime API. What do you think?

**Comment by frmz** [comment]
Well its quite straightforward, for time i have made an implementation here https://gist.github.com/frmz/0eeac13051e050ce0982 for the date its pretty close, problem is localization :)

**Comment by lincolnthree** [comment]
Closing as "Won't Fix". Thanks again!
