### ISSUE TITLE
Wrong output: `calculatePreciseDuration()` -> "moments ago 2 hours"

### ISSUE THREAD

**Issue by binwiederhier** [ocpsoft/prettytime#98]
Hi there and thanks for the great work. The following returns "moments ago 2 hours" when it should be "2 hours ago" or "2 hours 2 minutes ago":

```java
new PrettyTime().calculatePreciseDuration(
    new Date(System.currentTimeMillis() - 2*60*60*1000 - 2*60*1000))
```

**Comment by lincolnthree** [comment]
I've resolved this by changing "Just now" to be anything less than one minute, rather than anything less than five minutes.
