### ISSUE TITLE
Not showing "month ago" when February

### ISSUE THREAD

**Issue by magx2** [ocpsoft/prettytime#99]
Let's say today’s date is **1 March 2015** and I want to format **1 February 2015**. Instead of getting *month ago* I get *28 days ago*.

**Comment by lincolnthree** [comment]
Hmmm, this sounds like an issue with rounding tolerance. Could you provide a test case that reproduces this issue?

**Comment by magx2** [comment]
Ok, at Monday I will send smt to you.

**Comment by lincolnthree** [comment]
Thank you!

**Comment by magx2** [comment]
Sorry for the delay. In our project we are using ours units and this is the problem (I tested it without our units and it worked fine).

I'm closing issue because bug is not in the library.

BTW. could you look at my code and say  where I have mistake:

 ```
		private static final PrettyTime prettyTime = new PrettyTime(PL);

		[...]

		static {
				prettyTime.clearUnits();

				JustNow justNow = new JustNow();
				justNow.setMaxQuantity(1000L * 60L * 60L);
				prettyTime.registerUnit(justNow, new ResourcesTimeFormat(justNow));

				Hour hour = new Hour();
				prettyTime.registerUnit(hour, new HourTimeFormat(hour));

				Day day = new Day();
				prettyTime.registerUnit(day, new ResourcesTimeFormat(day));

				Month month = new Month();
				prettyTime.registerUnit(month, new MonthTimeFormat(month));

				Year year = new Year();
				prettyTime.registerUnit(year, new YearTimeFormat(year));
		}```
